apiVersion: v1
kind: Service
metadata: { name: james, namespace: platform }
spec:
  selector: { app: james }
  ports:
    - name: jmap
      port: 80
      targetPort: jmap
    - name: webadmin
      port: 8000
      targetPort: admin
  type: ClusterIP
