apiVersion: apps/v1
kind: Deployment
metadata: { name: revenue-console, namespace: web }
spec:
  replicas: 1
  selector: { matchLabels: { app: revenue-console } }
  template:
    metadata: { labels: { app: revenue-console } }
    spec:
      containers:
        - name: revenue-console
          image: rg.fr-par.scw.cloud/pandormedia/qoffice-revenue-console:preprod-latest
          ports: [ { containerPort: 80 } ]
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
