apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - gateway-secrets.yaml
  - redis-conn.yaml
  - db-secret.yaml
  - s3-credentials.yaml
  - admin-api-secrets.yaml
  - billing-secrets.yaml
  - indexer-secrets.yaml
  - notifications-secrets.yaml
  - qai-secrets.yaml
  - qcalendar-qcontacts-secrets.yaml
  - james-secrets.yaml
  - qmail-secrets.yaml
  - wopi-bridge-secrets.yaml
  - qmeet-secrets.yaml
  - qroot-secrets.yaml
