apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qai-ingress
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ "qai-api.preprod.qoffice.cloud" ]
      secretName: qai-tls
  rules:
    - host: qai-api.preprod.qoffice.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: qai, port: { number: 8180 } } }
