apiVersion: apps/v1
kind: Deployment
metadata: { name: qcalendar-qcontacts, namespace: platform }
spec:
  replicas: 1
  selector: { matchLabels: { app: qcalendar-qcontacts } }
  template:
    metadata: { labels: { app: qcalendar-qcontacts } }
    spec:
      containers:
        - name: qcalendar-qcontacts
          image: rg.fr-par.scw.cloud/pandormedia/qoffice-qcalendar-qcontacts:preprod-latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: qcalendar-qcontacts-secrets
                  key: DATABASE_URL
            - name: DB_HOST
              value: postgres.data.svc.cluster.local
            - name: DB_PORT
              value: "5432"
