apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qroot-api-ingress
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ "qroot-api.preprod.qoffice.cloud" ]
      secretName: qroot-api-tls
  rules:
    - host: qroot-api.preprod.qoffice.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: qroot, port: { number: 8093 } } }
