apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - clamav.yaml
  - jobs/qmail-email-listener
  - jobs/qmail-scheduled-worker
  - jobs/qmail-virus-scan-worker
  - jobs/qmail-audit-archival
images:
  - name: rg.fr-par.scw.cloud/pandormedia/qoffice-qmail
    newTag: preprod-300b02069591f7a263e05fcd954eb27cc342d750
