apiVersion: apps/v1
kind: Deployment
metadata: { name: wopi-bridge, namespace: platform }
spec:
  replicas: 1
  selector: { matchLabels: { app: wopi-bridge } }
  template:
    metadata: { labels: { app: wopi-bridge } }
    spec:
      containers:
        - name: wopi-bridge
          image: rg.fr-par.scw.cloud/pandormedia/qoffice-wopi-bridge:preprod-latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: S3_ENDPOINT
              value: https://s3.fr-par.scw.cloud
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_KEY
            - name: S3_REGION
              value: fr-par
            - name: S3_SSE
              value: SSE-C
            - name: S3_SSE_C_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SSE_C_KEY
            - name: S3_SSE_C_KEY_MD5
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SSE_C_KEY_MD5
            - name: S3_SSE_C_SCOPE
              value: user
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wopi-bridge-secrets
                  key: JWT_SECRET
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: wopi-bridge-secrets
                  key: DATABASE_URL
            - name: KEYCLOAK_URL
              value: https://keycloak.preprod.qoffice.cloud
            - name: KEYCLOAK_REALM
              value: qoffice-preprod
            - name: OIDC_ISSUER_URL
              value: https://keycloak.preprod.qoffice.cloud/realms/qoffice-preprod
